# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/dogs/test/cluster/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/dogs/test/storage/s3/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/dogs-ua/test/cluster/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/dogs-ua/test/storage/s3/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/cats/prod/cluster/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/cats/prod/storage/s3/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/cats/test/cluster/"
  - package-ecosystem: "terraform" # See documentation for possible values
    schedule:
      interval: "daily"
    registries:
      - terraform-aws-modules
    directory: "/cats/test/storage/s3/"
     
registries:
  terraform-aws-modules: # Define access for a private registry
    type: git
    url: https://github.com/
    username: x-access-token
    password: ${{secrets.GITHUB_TOKEN}}
