name: Plan All Environments
on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  terragrunt:
    name: Terragrunt
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.name }}
    container:
      image: alpine:latest
    strategy:
      matrix: #["cats/test", "cats/prod"]
        include:
          - name: cats-test
            workdir: cats/test
          - name: cats-prod
            workdir: cats/prod
          - name: dogs-test
            workdir: dogs/test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Plan
        # working-directory: ${{ matrix.workdir }})
        run: |
          ls
          cd ${{ matrix.workdir}}
          pwd

      - name: Apply
        if: github.ref == 'refs/heads/$default-branch' && github.event_name == 'push'
        working-directory: ${{ matrix.workdir}}
        run: |
          pwd
          echo "apply"
