name: cats-test
on:
  push:
    paths:
      - 'cats/test/*'
  workflow_dispatch:
      paths:
      - 'cats/test/*'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Plan
        run: |
          cd cats/test
          pwd
          echo "plan"

  apply:
    name: apply
    runs-on: ubuntu-latest
    environment:
      name: cats-test
    needs: [plan]
    container:
      image: alpine:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply
        run: |
          cd cats/test
          pwd
          echo "apply"
